version: '3.9'

services:
  back:
    build:
      context: ./KodalibApi
    ports:
      - "81:80"
    restart: always
    depends_on:
      - db

  front:
    build:
      context: ./kodalibfront
    ports:
      - "80:80"
    restart: always

  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=monvormo
    restart: always
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
  
volumes:
    db:
