// <auto-generated />
using System;
using KodalibApi.Dal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KodalibApi.Dal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KodalibApi.Data.Models.Comments.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("Rate")
                        .HasColumnType("integer")
                        .HasColumnName("rate");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("Id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.Comments.FilmComment", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer")
                        .HasColumnName("film_id");

                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<int>("CommentsId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "CommentId");

                    b.HasIndex("CommentsId");

                    b.ToTable("film_comment");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.Comments.SeriesComment", b =>
                {
                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("film_id");

                    b.Property<int>("CommentsId")
                        .HasColumnType("integer");

                    b.HasKey("CommentId", "SeriesId");

                    b.HasIndex("CommentsId");

                    b.HasIndex("SeriesId");

                    b.ToTable("series_comment");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.FIlmTables.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountRate")
                        .HasColumnType("integer")
                        .HasColumnName("count_rate");

                    b.Property<string>("Duration")
                        .HasColumnType("text")
                        .HasColumnName("duration");

                    b.Property<string>("KinopoiskId")
                        .HasColumnType("text")
                        .HasColumnName("kinopoisk_id");

                    b.Property<string>("KinopoiskRating")
                        .HasColumnType("text")
                        .HasColumnName("kinopoisk_rating");

                    b.Property<string>("KodalibRating")
                        .HasColumnType("text")
                        .HasColumnName("kodalib_rating");

                    b.Property<string>("Plot")
                        .HasColumnType("text")
                        .HasColumnName("plot");

                    b.Property<string>("Poster")
                        .HasColumnType("text")
                        .HasColumnName("poster");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.Property<string>("YoutubeTrailer")
                        .HasColumnType("text")
                        .HasColumnName("youtube_trailer");

                    b.HasKey("Id");

                    b.ToTable("films");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.FIlmTables.FilmCountry", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer")
                        .HasColumnName("film_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.HasKey("FilmId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("film_country");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.FilmTables.FilmGenre", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer")
                        .HasColumnName("film_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasKey("FilmId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("film_genre");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.FIlmTables.FilmVoiceover", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer")
                        .HasColumnName("film_id");

                    b.Property<int>("VoiceoverId")
                        .HasColumnType("integer")
                        .HasColumnName("voiceover_id");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FilmId", "VoiceoverId");

                    b.HasIndex("VoiceoverId");

                    b.ToTable("film_voiceover");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("genres");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.Character", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer")
                        .HasColumnName("film_id");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actors_id");

                    b.HasKey("FilmId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("character");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.Director", b =>
                {
                    b.Property<int>("DirectorId")
                        .HasColumnType("integer")
                        .HasColumnName("director_id");

                    b.Property<int>("FilmId")
                        .HasColumnType("integer")
                        .HasColumnName("film_id");

                    b.Property<int>("DirectorPersonId")
                        .HasColumnType("integer");

                    b.HasKey("DirectorId", "FilmId");

                    b.HasIndex("DirectorPersonId");

                    b.HasIndex("FilmId");

                    b.ToTable("directors_films");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.FilmPeople.Writer", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer")
                        .HasColumnName("film_id");

                    b.Property<int>("WriterId")
                        .HasColumnType("integer")
                        .HasColumnName("writer_id");

                    b.Property<int>("WriterPersonId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "WriterId");

                    b.HasIndex("WriterPersonId");

                    b.ToTable("writers_films");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PersonKinopoiskId")
                        .HasColumnType("text")
                        .HasColumnName("person_kinopoisk_id");

                    b.HasKey("Id");

                    b.ToTable("person");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.SeriesPeople.CharacterSeries", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("series_id");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actors_id");

                    b.HasKey("SeriesId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("character_series");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.SeriesPeople.DirectorSeries", b =>
                {
                    b.Property<int>("DirectorId")
                        .HasColumnType("integer")
                        .HasColumnName("director_id");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("series_id");

                    b.Property<int>("DirectorPersonId")
                        .HasColumnType("integer");

                    b.HasKey("DirectorId", "SeriesId");

                    b.HasIndex("DirectorPersonId");

                    b.HasIndex("SeriesId");

                    b.ToTable("director_series");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.SeriesPeople.WriterSeries", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("series_id");

                    b.Property<int>("WriterId")
                        .HasColumnType("integer")
                        .HasColumnName("writer_id");

                    b.Property<int>("WriterPersonId")
                        .HasColumnType("integer");

                    b.HasKey("SeriesId", "WriterId");

                    b.HasIndex("WriterPersonId");

                    b.ToTable("writer_series");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.Episodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<short>("NumberEpisode")
                        .HasColumnType("smallint")
                        .HasColumnName("number_episode");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<string>("VideoLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("episodes");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberSeason")
                        .HasColumnType("integer");

                    b.Property<int>("VoiceoverId")
                        .HasColumnType("integer")
                        .HasColumnName("voiceover_id");

                    b.Property<int>("VoiceoverId1")
                        .HasColumnType("integer");

                    b.Property<int>("VoiceoverSeriesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VoiceoverSeriesId", "VoiceoverId1");

                    b.ToTable("season");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountRate")
                        .HasColumnType("integer")
                        .HasColumnName("count_rate");

                    b.Property<string>("Duration")
                        .HasColumnType("text")
                        .HasColumnName("duration");

                    b.Property<string>("KinopoiskId")
                        .HasColumnType("text")
                        .HasColumnName("kinopoisk_id");

                    b.Property<string>("KinopoiskRating")
                        .HasColumnType("text")
                        .HasColumnName("kinopoisk_rating");

                    b.Property<string>("KodalibRating")
                        .HasColumnType("text")
                        .HasColumnName("kodalib_rating");

                    b.Property<string>("Plot")
                        .HasColumnType("text")
                        .HasColumnName("plot");

                    b.Property<string>("Poster")
                        .HasColumnType("text")
                        .HasColumnName("poster");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.Property<string>("YoutubeTrailer")
                        .HasColumnType("text")
                        .HasColumnName("youtube_trailer");

                    b.HasKey("Id");

                    b.ToTable("series");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.SeriesCountries", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("series_id");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.HasKey("SeriesId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("series_countries");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.SeriesGenres", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("series_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genres_id");

                    b.HasKey("SeriesId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("series_genres");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.SeriesVoiceover", b =>
                {
                    b.Property<int>("SeriesId")
                        .HasColumnType("integer")
                        .HasColumnName("series_id");

                    b.Property<int>("VoiceoverId")
                        .HasColumnType("integer")
                        .HasColumnName("voiceover_id");

                    b.Property<int>("CountEpisodes")
                        .HasColumnType("integer")
                        .HasColumnName("count_episodes");

                    b.Property<int>("CountSeasons")
                        .HasColumnType("integer")
                        .HasColumnName("count_season");

                    b.HasKey("SeriesId", "VoiceoverId");

                    b.HasIndex("VoiceoverId");

                    b.ToTable("series_voiceover");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.VoiceoverTable.Voiceover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("voiceover");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.Comments.FilmComment", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.Comments.Comments", "Comments")
                        .WithMany("FilmComments")
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.FIlmTables.Film", "Films")
                        .WithMany("Comments")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("Films");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.Comments.SeriesComment", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.Comments.Comments", "Comments")
                        .WithMany("SeriesComments")
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.SeriesTable.Series", "Series")
                        .WithMany("Comments")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.FIlmTables.FilmCountry", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.Country", "Country")
                        .WithMany("FilmsList")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.FIlmTables.Film", "Film")
                        .WithMany("CountriesList")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.FilmTables.FilmGenre", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.FIlmTables.Film", "Film")
                        .WithMany("GenresList")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.Genre", "Genre")
                        .WithMany("FilmsList")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.FIlmTables.FilmVoiceover", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.FIlmTables.Film", "Film")
                        .WithMany("Voiceovers")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.VoiceoverTable.Voiceover", "Voiceover")
                        .WithMany("Films")
                        .HasForeignKey("VoiceoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Voiceover");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.Character", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.PeopleTables.Person", "Actor")
                        .WithMany("Films")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.FIlmTables.Film", "Film")
                        .WithMany("Characters")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.Director", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.PeopleTables.Person", "DirectorPerson")
                        .WithMany("Directors")
                        .HasForeignKey("DirectorPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.FIlmTables.Film", "Film")
                        .WithMany("Directors")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectorPerson");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.FilmPeople.Writer", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.FIlmTables.Film", "Film")
                        .WithMany("Writers")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.PeopleTables.Person", "WriterPerson")
                        .WithMany("Writers")
                        .HasForeignKey("WriterPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("WriterPerson");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.SeriesPeople.CharacterSeries", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.PeopleTables.Person", "Actor")
                        .WithMany("Series")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.SeriesTable.Series", "Series")
                        .WithMany("Characters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.SeriesPeople.DirectorSeries", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.PeopleTables.Person", "DirectorPerson")
                        .WithMany("DirectorSeries")
                        .HasForeignKey("DirectorPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.SeriesTable.Series", "Series")
                        .WithMany("Directors")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectorPerson");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.SeriesPeople.WriterSeries", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.SeriesTable.Series", "Series")
                        .WithMany("Writers")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.PeopleTables.Person", "WriterPerson")
                        .WithMany("WriterSeries")
                        .HasForeignKey("WriterPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("WriterPerson");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.Episodes", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.SeriesTable.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.Season", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.SeriesTable.SeriesVoiceover", "Voiceover")
                        .WithMany("Seasons")
                        .HasForeignKey("VoiceoverSeriesId", "VoiceoverId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voiceover");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.SeriesCountries", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.Country", "Country")
                        .WithMany("SeriesList")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.SeriesTable.Series", "Series")
                        .WithMany("Countries")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.SeriesGenres", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.Genre", "Genre")
                        .WithMany("SeriesList")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.SeriesTable.Series", "Series")
                        .WithMany("Genres")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.SeriesVoiceover", b =>
                {
                    b.HasOne("KodalibApi.Data.Models.SeriesTable.Series", "Series")
                        .WithMany("Voiceovers")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodalibApi.Data.Models.VoiceoverTable.Voiceover", "Voiceover")
                        .WithMany("Series")
                        .HasForeignKey("VoiceoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("Voiceover");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.Comments.Comments", b =>
                {
                    b.Navigation("FilmComments");

                    b.Navigation("SeriesComments");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.Country", b =>
                {
                    b.Navigation("FilmsList");

                    b.Navigation("SeriesList");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.FIlmTables.Film", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Comments");

                    b.Navigation("CountriesList");

                    b.Navigation("Directors");

                    b.Navigation("GenresList");

                    b.Navigation("Voiceovers");

                    b.Navigation("Writers");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.Genre", b =>
                {
                    b.Navigation("FilmsList");

                    b.Navigation("SeriesList");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.PeopleTables.Person", b =>
                {
                    b.Navigation("DirectorSeries");

                    b.Navigation("Directors");

                    b.Navigation("Films");

                    b.Navigation("Series");

                    b.Navigation("WriterSeries");

                    b.Navigation("Writers");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.Series", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Comments");

                    b.Navigation("Countries");

                    b.Navigation("Directors");

                    b.Navigation("Genres");

                    b.Navigation("Voiceovers");

                    b.Navigation("Writers");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.SeriesTable.SeriesVoiceover", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("KodalibApi.Data.Models.VoiceoverTable.Voiceover", b =>
                {
                    b.Navigation("Films");

                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
